# Generated by Django 3.0.4 on 2020-04-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
    ]
