# Generated by Django 3.0.4 on 2020-04-15 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
